alias WOWC="${HOME}/scripts/wow_launch.sh Chromiecraft"
alias WOWCHD="${HOME}/scripts/wow_launch.sh ChromiecraftHD"
alias WOWL="${HOME}/scripts/wow_launch.sh Local"
alias WOWLHD="${HOME}/scripts/wow_launch.sh LocalHD"
alias WOWLC="${HOME}/scripts/wow_launch.sh CMangos"
alias WOWLT="${HOME}/scripts/wow_launch.sh Trinity"
