alias WOW="export ID=2;export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh"
alias WOWC="export ID=2; export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh Chromiecraft"
alias WOWC2="export ID=2; export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh Chromiecraft2"
alias WOWW="export ID=2; export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh Warmane"
alias WOWW2="export ID=2; export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh Warmane2"
alias WOWL="export ID=2; export FOLDER=wow335;/home/${USER}/scripts/launch_wow.sh Local"
alias WOWH="export ID=3; export FOLDER=wow112;/home/${USER}/scripts/launch_wow.sh Henhouse"
alias WOWT="export ID=4; export FOLDER=wow112turtle;/home/${USER}/scripts/launch_wow.sh Turtle"